[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ParaDistRay"
authors = [{name = "Graziella", email = "navinkumar.m2020@vitstudent.ac.in"}]
dynamic = ["version", "description"]